services:
  backend:
    build: ./backend
    container_name: discord_clone_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    networks:
      - discord-network

  frontend:
    build: ./Frontend
    container_name: discord_clone_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - discord-network
  postgres:
    image: postgres:16
    container_name: discord_clone_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discord_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - discord-network

  redis:
    image: redis:7
    container_name: discord_clone_redis
    networks:
      - discord-network

networks:
  discord-network:
    driver: bridge

volumes:
  postgres_data:
