@echo off
cd backend
set DB_HOST=localhost
set DB_PORT=5432
set DB_NAME=rudis
set DB_USER=postgres
set DB_PASSWORD=password
set REDIS_HOST=localhost
set REDIS_PORT=6379
set JWT_SECRET=your_super_secret_jwt_key_here
set JWT_EXPIRES_IN=7d
set PORT=5000
set NODE_ENV=development
set FRONTEND_URL=http://localhost:3000
set CORS_ORIGIN=http://localhost:3000
set CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
set CORS_HEADERS=Content-Type,Authorization,X-Requested-With
node src/app.js