// backend/src/services/aiService.js
const fs = require('fs').promises;
const path = require('path');
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

const { GoogleGenerativeAI } = require('@google/generative-ai');
const Groq = require('groq-sdk').default;

class AIService {
  constructor() {
    // ===== Groq (PRIMARY) =====
    if (process.env.GROQ_API_KEY) {
      this.groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
      console.log('✅ Groq AI инициализирован (PRIMARY)');
    }

    // ===== Gemini (backup) =====
    if (process.env.GOOGLE_API_KEY) {
      try {
        const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY);
        this.gemini = genAI.getGenerativeModel({ model: 'gemini-pro' });
        console.log('✅ Gemini AI инициализирован (backup)');
      } catch (err) {
        console.warn('⚠️ Gemini init error:', err.message);
      }
    }
  }

  // ============================
  // CHAT METHODS
  // ============================

  async chat(message, history = []) {
    if (this.groq) return this.groqChat(message, history);
    if (this.gemini) return this.geminiChat(message, history);
    throw new Error('AI не инициализирован');
  }

  async groqChat(message, history = []) {
    const messages = [
      ...history.map(m => ({ role: m.role, content: m.content })),
      { role: 'user', content: message }
    ];

    const completion = await this.groq.chat.completions.create({
      messages,
      model: 'llama-3.3-70b-versatile',
      temperature: 0.7,
      max_tokens: 2048,
    });

    return completion.choices[0].message.content;
  }

  async geminiChat(message, history = []) {
    const geminiHistory = history.map(msg => ({
      role: msg.role === 'user' ? 'user' : 'model',
      parts: [{ text: msg.content }]
    }));

    const chat = this.gemini.startChat({ history: geminiHistory });
    const result = await chat.sendMessage(message);
    return result.response.text();
  }

  // ============================
  // TOOLS / INSTRUMENTS
  // ============================

  tools = {
    readFile: async (task, filePath) => {
      const abs = this.safePath(filePath);
      const content = await fs.readFile(abs, 'utf8');
      task.logs.push({ time: new Date().toISOString(), message: `📖 Прочитал файл ${filePath}` });
      return content;
    },

    writeFile: async (task, filePath, content) => {
      const abs = this.safePath(filePath);
      await fs.mkdir(path.dirname(abs), { recursive: true });
      await fs.writeFile(abs, content, 'utf8');
      task.logs.push({ time: new Date().toISOString(), message: `✏️ Записал файл ${filePath}` });
    },

    runCommand: async (task, command) => {
      task.logs.push({ time: new Date().toISOString(), message: `⚡ Выполняю команду: ${command}` });
      const { stdout, stderr } = await execPromise(command, { cwd: process.cwd(), timeout: 60000 });
      task.logs.push({ time: new Date().toISOString(), message: `📄 Результат команды:\n${stdout}\n${stderr}` });
      return { stdout, stderr };
    },

    analyzeCode: async (task, code, language = 'javascript') => {
      const result = await this.analyzeCode(code, language);
      task.logs.push({ time: new Date().toISOString(), message: `🧪 Проанализирован код` });
      return result;
    }
  };

  // ============================
  // TASK EXECUTION
  // ============================

  async executeTaskAsync(task) {
    task.status = 'in_progress';
    task.logs.push({ time: new Date().toISOString(), message: '🚀 Начало выполнения задачи' });

    try {
      // ===== STEP 1: Planning =====
      const planPrompt = `
Ты — AI разработчик. Составь план выполнения задачи:

Задача: ${task.title}
Описание: ${task.description}
Тип: ${task.type}

Дай пошаговый план в формате:
1. [действие]
2. [действие]
...
`;
      const plan = await this.chat(planPrompt);
      task.logs.push({ time: new Date().toISOString(), message: `📋 План:\n${plan}` });

      // ===== STEP 2: Execute Plan =====
      // Очень простой вариант: ищем ключевые слова для инструментов
      const lines = plan.split(/\r?\n/).map(l => l.trim()).filter(Boolean);

      for (const line of lines) {
        if (/read/i.test(line)) {
          const match = line.match(/read\s+(.+)/i);
          if (match) {
            await this.tools.readFile(task, match[1]);
          }
        } else if (/write/i.test(line)) {
          const match = line.match(/write\s+(.+)/i);
          if (match) {
            await this.tools.writeFile(task, match[1], '// TODO: generated by AI');
          }
        } else if (/run/i.test(line)) {
          const match = line.match(/run\s+(.+)/i);
          if (match) await this.tools.runCommand(task, match[1]);
        } else if (/analyze/i.test(line)) {
          const match = line.match(/analyze\s+(.+)/i);
          if (match) {
            const code = await this.tools.readFile(task, match[1]);
            await this.tools.analyzeCode(task, code, this.getLanguageFromPath(match[1]));
          }
        }
      }

      task.status = 'done';
      task.logs.push({ time: new Date().toISOString(), message: '🎉 Задача выполнена успешно' });

    } catch (err) {
      task.status = 'failed';
      task.logs.push({ time: new Date().toISOString(), message: `❌ Ошибка: ${err.message}` });
    }

    task.updatedAt = new Date().toISOString();
  }

  // ============================
  // CODE ANALYSIS
  // ============================

  async analyzeCode(code, language = 'javascript') {
    const prompt = `
Ты эксперт по программированию. Проанализируй следующий ${language} код:

\`\`\`${language}
${code}
\`\`\`

Верни JSON с багами, безопасностью, производительностью, best practices и рефакторингом.
`;
    const response = await this.chat(prompt);
    try {
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      return JSON.parse(jsonMatch[0]);
    } catch {
      return { error: 'Не удалось распарсить анализ', raw: response };
    }
  }

  // ============================
  // HELPERS
  // ============================

  safePath(filePath) {
    const abs = path.resolve(filePath);
    const root = process.cwd();
    if (!abs.startsWith(root)) throw new Error('Access denied');
    return abs;
  }

  getLanguageFromPath(filePath) {
    const ext = path.extname(filePath);
    const map = { '.js': 'javascript', '.ts': 'typescript', '.py': 'python', '.java': 'java' };
    return map[ext] || 'javascript';
  }

  getStatus() {
    return { groq: !!this.groq, gemini: !!this.gemini, available: !!(this.groq || this.gemini) };
  }
}

module.exports = new AIService();
